version: '3.7'

services:
  # USŁUGA APLIKACJI (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: audiobook-php-fpm # Nowa nazwa obrazu
    container_name: audiobook_app
    restart: unless-stopped
    environment:
      # WAŻNE: Wymagane przez Symfony, ale nie jest używane bezpośrednio do łączenia
      SERVER_NAME: ${SERVER_NAME:-localhost}
      REDIS_URL: 'redis://redis:6379'
      # Użyjemy domyślnych danych połączenia
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-pass}@db:3306/${MYSQL_DATABASE:-mydatabase}?serverVersion=10.11&charset=utf8mb4

      # Mercure jest teraz opcjonalny, usuń jeśli nie używasz
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_URL: http://app/.well-known/mercure # Zmieniony host na 'app'
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure

    # Mapujemy kod źródłowy
    volumes:
      - .:/var/www/html
      # - /var/www/html/vendor # Opcjonalnie: aby nie kopiować vendor z hosta, jeśli budujesz w Dockerfile

  # USŁUGA SERWERA WWW (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: audiobook_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Mapowanie portu 80 kontenera na 8080 hosta
    volumes:
      # Mapowanie lokalnego folderu z kodem i konfiguracji Nginx
      - .:/var/www/html:ro # Tylko do odczytu
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - redis

  # USŁUGA BAZY DANYCH (MariaDB)
  db:
    image: mariadb:10.11
    container_name: audiobook_db
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
  redis:
    image: redis:7.2-alpine
    container_name: audiobook_redis
    restart: always
    volumes:
      - redis_data:/data
volumes:
  db-data:
  redis_data: