version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: audiobook-php-fpm
    container_name: audiobook_app
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-pass}@db:3306/${MYSQL_DATABASE:-mydatabase}?serverVersion=10.11&charset=utf8mb4
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: audiobook_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.11
    container_name: audiobook_db
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
  redis:
    image: redis:7.2-alpine
    container_name: audiobook_redis
    restart: always
    volumes:
      - redis_data:/data
volumes:
  db-data:
  redis_data: